name: app_frontend
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^3.2.2
  bloc: ^8.0.2
  connectivity: ^3.0.6
  cupertino_icons:
  dartz: ^0.10.1
  dio: ^4.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  dropdown_button2: ^2.1.0
  flutter_bloc: ^8.0.1
  flutter_storage_path: ^1.0.4
  image_picker:
  get: ^4.6.5
  get_storage:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http:
  modal_progress_hud_nsn:
  shared_preferences: ^2.1.1


dev_dependencies:
  auto_route_generator: null
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Medium.ttf
    - family: Raleway_main
      fonts:
        - asset: assets/font/Raleway.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
